apiVersion: v1
kind: Service
metadata:
  name: furweb-service
spec:
  selector:
    app: furweb
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30007
    - name: api
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort

