name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tanmoy037/furweb:${{ github.sha }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push tanmoy037/furweb:${{ github.sha }}
          echo "::set-env name=DOCKER_TAG::${{ github.sha }}"

  update-manifest:
    runs-on: ubuntu-latest 
    needs: ['build']
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Tanmoy037/Furniture-website_manifiest
          ref: main
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "tanmoysantra67@gmail.com"
          git config --global user.name "Tanmoy037"

      - name: Get Docker image digest
        id: tag
        run: echo "::set-output name=digest::$(docker inspect tanmoy037/furweb:${{ env.DOCKER_TAG }} --format={{.RepoDigests}} | cut -d '@' -f2)"

      - name: Update deployment.yml file
        run: |
          new_tag=${{ env.DOCKER_TAG }}
          sed -i "s|tanmoy037/furweb:|tanmoy037/furweb:${new_tag}|" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment.yml with new - ${{ github.sha }}"
          git push origin main