name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t tanmoy037/furweb:${{ github.sha }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push tanmoy037/furweb:${{ github.sha }}
      - name: Update deployment.yml with new image tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: tanmoy037/furweb:${{ github.sha }},tanmoy037/furweb:latest
        id: tag
      - name: Checkout manifest repository
        uses: actions/checkout@v2
        with:
          repository: Tanmoy037/Furniture-website_manifest
      - name: Update deployment.yml file
        run: |
          sed -i "s/tanmoy037\/furweb:[^\\s]*/${{ steps.tag.outputs.digest }}/g" deployment.yml
          git config --global user.email tanmoysantra67@gmail.com 
          git config --global user.name Tanmoy037
          git add deployment.yml
          git commit -m "Update deployment.yml with new image tag"
          git push
