name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Define formatTime function
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            function formatTime(date, format) {
              const dt = new Date(date);
              let yyyy = dt.getFullYear();
              let mm = dt.getMonth() + 1;
              let dd = dt.getDate();
              let hh = dt.getHours();
              let mi = dt.getMinutes();
              let ss = dt.getSeconds();

              if (mm < 10) {
                mm = '0' + mm;
              }
              if (dd < 10) {
                dd = '0' + dd;
              }
              if (hh < 10) {
                hh = '0' + hh;
              }
              if (mi < 10) {
                mi = '0' + mi;
              }
              if (ss < 10) {
                ss = '0' + ss;
              }

              if (format === 'yyyyMMddhhmmss') {
                return `${yyyy}${mm}${dd}${hh}${mi}${ss}`;
              }
              return dt.toISOString();
            }
          
      - name: Build the Docker image
        run: docker build -t tanmoy037/furweb:${{ formatTime(now(), 'yyyyMMddhhmmss') }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push tanmoy037/furweb:${{ env.DOCKER_TAG }}
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }}" >> $GITHUB_ENV

  update-manifest:
    runs-on: ubuntu-latest 
    needs: ['build']
    env: 
      GITHUB_TOKEN: ${{ secrets.G_TOKEN}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Tanmoy037/Furniture-website_manifiest
          ref: main
          token: ${{ secrets.G_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "tanmoysantra67@gmail.com"
          git config --global user.name "Tanmoy037"

      - name: Get Docker image digest
        id: tag
        run: echo "::set-output name=digest::$(docker inspect tanmoy037/furweb:${{ env.DOCKER_TAG }} --format={{.RepoDigests}} | cut -d '@' -f2)"

      - name: Update deployment.yml file
        run: |
          new_tag=${{ env.DOCKER_TAG }}
          sed -i "s|tanmoy037/furweb:|tanmoy037/furweb:${new_tag}|" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment.yml with new - ${{ github.sha }}"
          git push origin main
