name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t tanmoy037/furweb:${{ github.sha }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push tanmoy037/furweb:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest 
    needs: ['build-and-push-Docker-image']
    steps:
      - uses: actions/checkout@v3
        with:   
          repository: Tanmoy037/Furniture-website_manifiest
          ref: main
          token: ${{ secrets.G_TOKEN }}
      - name: Update deployment.yml file
        run: |
          git config --global user.email tanmoysantra67@gmail.com 
          git config --global user.name Tanmoy037
          new_tag=$(echo "${{ steps.tag.outputs.digest }}" | cut -d'/' -f2)
          sed -i "s|tanmoy037/furweb:[^[:space:]]*|tanmoy037/furweb:${new_tag}|g" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment.yml with new image tag"
          git push origin main

          
